# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import product_pb2 as product__pb2
import grpc_client.grpc.product_pb2 as product__pb2


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProductList = channel.unary_unary(
            "/product.ProductService/ProductList",
            request_serializer=product__pb2.ProductListRequest.SerializeToString,
            response_deserializer=product__pb2.ProductListResponse.FromString,
        )
        self.ProductDetail = channel.unary_unary(
            "/product.ProductService/ProductDetail",
            request_serializer=product__pb2.ProductDetailRequest.SerializeToString,
            response_deserializer=product__pb2.ProductDetailResponse.FromString,
        )
        self.ProductCreate = channel.unary_unary(
            "/product.ProductService/ProductCreate",
            request_serializer=product__pb2.ProductCreateRequest.SerializeToString,
            response_deserializer=product__pb2.ProductCreateResponse.FromString,
        )
        self.ProductUpdate = channel.unary_unary(
            "/product.ProductService/ProductUpdate",
            request_serializer=product__pb2.ProductUpdateRequest.SerializeToString,
            response_deserializer=product__pb2.ProductUpdateResponse.FromString,
        )
        self.ProductDelete = channel.unary_unary(
            "/product.ProductService/ProductDelete",
            request_serializer=product__pb2.ProductDeleteRequest.SerializeToString,
            response_deserializer=product__pb2.ProductDeleteResponse.FromString,
        )
        self.SumPrice = channel.unary_unary(
            "/product.ProductService/SumPrice",
            request_serializer=product__pb2.SumPriceRequest.SerializeToString,
            response_deserializer=product__pb2.SumPriceResponse.FromString,
        )


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProductList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProductDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProductCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProductUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProductDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SumPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ProductList": grpc.unary_unary_rpc_method_handler(
            servicer.ProductList,
            request_deserializer=product__pb2.ProductListRequest.FromString,
            response_serializer=product__pb2.ProductListResponse.SerializeToString,
        ),
        "ProductDetail": grpc.unary_unary_rpc_method_handler(
            servicer.ProductDetail,
            request_deserializer=product__pb2.ProductDetailRequest.FromString,
            response_serializer=product__pb2.ProductDetailResponse.SerializeToString,
        ),
        "ProductCreate": grpc.unary_unary_rpc_method_handler(
            servicer.ProductCreate,
            request_deserializer=product__pb2.ProductCreateRequest.FromString,
            response_serializer=product__pb2.ProductCreateResponse.SerializeToString,
        ),
        "ProductUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.ProductUpdate,
            request_deserializer=product__pb2.ProductUpdateRequest.FromString,
            response_serializer=product__pb2.ProductUpdateResponse.SerializeToString,
        ),
        "ProductDelete": grpc.unary_unary_rpc_method_handler(
            servicer.ProductDelete,
            request_deserializer=product__pb2.ProductDeleteRequest.FromString,
            response_serializer=product__pb2.ProductDeleteResponse.SerializeToString,
        ),
        "SumPrice": grpc.unary_unary_rpc_method_handler(
            servicer.SumPrice,
            request_deserializer=product__pb2.SumPriceRequest.FromString,
            response_serializer=product__pb2.SumPriceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "product.ProductService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProductList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.ProductService/ProductList",
            product__pb2.ProductListRequest.SerializeToString,
            product__pb2.ProductListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ProductDetail(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.ProductService/ProductDetail",
            product__pb2.ProductDetailRequest.SerializeToString,
            product__pb2.ProductDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ProductCreate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.ProductService/ProductCreate",
            product__pb2.ProductCreateRequest.SerializeToString,
            product__pb2.ProductCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ProductUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.ProductService/ProductUpdate",
            product__pb2.ProductUpdateRequest.SerializeToString,
            product__pb2.ProductUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ProductDelete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.ProductService/ProductDelete",
            product__pb2.ProductDeleteRequest.SerializeToString,
            product__pb2.ProductDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SumPrice(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.ProductService/SumPrice",
            product__pb2.SumPriceRequest.SerializeToString,
            product__pb2.SumPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
