@baseUrl = http://127.0.0.1:6543/api/v1/product

### Get all products
GET {{baseUrl}}

### Get product by id
GET {{baseUrl}}?id=1

### Post a product
POST {{baseUrl}}

{
    "name": "product 2",
    "price": 10000,
    "description": "product 1 description",
    "stock": 10,
    "image": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}

### Update a product
PUT {{baseUrl}}

{
    "id": 2,
    "name": "product 10",
    "price": 10000,
    "description": "product 1 description",
    "stock": 10,
    "image": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}

### Delete a product
DELETE {{baseUrl}}

{
    "id": 1
}